"""empty message

Revision ID: 5830798005f4
Revises: d02f85dbdcba
Create Date: 2023-03-10 19:06:51.158405

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5830798005f4'
down_revision = 'd02f85dbdcba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('planets',
    sa.Column('planet_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('terrain', sa.String(length=250), nullable=True),
    sa.Column('climate', sa.String(length=250), nullable=True),
    sa.Column('population', sa.String(length=250), nullable=True),
    sa.Column('diameter', sa.String(length=250), nullable=True),
    sa.PrimaryKeyConstraint('planet_id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('characters',
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('homeworld_id', sa.Integer(), nullable=True),
    sa.Column('gender', sa.String(length=10), nullable=True),
    sa.Column('hairColor', sa.String(length=250), nullable=True),
    sa.Column('skinColor', sa.String(length=250), nullable=True),
    sa.Column('eyeColor', sa.String(length=250), nullable=True),
    sa.ForeignKeyConstraint(['homeworld_id'], ['planets.planet_id'], ),
    sa.PrimaryKeyConstraint('character_id')
    )
    op.create_table('starships',
    sa.Column('starship_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('pilot_id', sa.Integer(), nullable=True),
    sa.Column('model', sa.String(length=500), nullable=True),
    sa.Column('manufacturer', sa.String(length=250), nullable=True),
    sa.Column('cost', sa.Integer(), nullable=True),
    sa.Column('topSpeed', sa.Integer(), nullable=True),
    sa.Column('maxCargo', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['pilot_id'], ['characters.character_id'], ),
    sa.PrimaryKeyConstraint('starship_id')
    )
    op.create_table('favourites',
    sa.Column('favourite_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('character_id', sa.Integer(), nullable=True),
    sa.Column('planet_id', sa.Integer(), nullable=True),
    sa.Column('starship_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['character_id'], ['characters.character_id'], ),
    sa.ForeignKeyConstraint(['planet_id'], ['planets.planet_id'], ),
    sa.ForeignKeyConstraint(['starship_id'], ['starships.starship_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('favourite_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('favourites')
    op.drop_table('starships')
    op.drop_table('characters')
    op.drop_table('planets')
    # ### end Alembic commands ###
